---


dataset: 'celeba'
num_rounds: 100
num_clients: 50
batch_size: 64
num_classes: 10
target_label: 7
num_clients_per_round_fit: 15
num_clients_per_round_eval: 15
device: "cuda:0"
config_fit:
  poisoning_rate: 0.7
  lr: 0.01      
  momentum: 0.9
  local_epochs: 5
  proximal_mu: 2.0  #0.0 if FedAvg (IID)  #2.0 if FedProx (Non-IID)

dataset_config:
  ratio_benign_client: 0.6
  iid: true
  balance: false
  power_law: false
  dirichlet: true
  alpha: 0.9
